---
title: "Document for creating histograms"
author: "Cassi Hung"
date: "2023-04-04"
output: html_document
---

For this week, we are creating histograms for all of the possible values of ystar under each condition.

```{r firsthistogram}

#Vary the sample size -- set value of N
#Vary the degree of unequal thresholds -- choose between mild, moderate, and severe
#Vary the size of the predictor effects of eta -- b1 and b2
### 2 Conditions: [.1, .2, .9]; [.2, .4, .8]
#Vary the link between eta and ystar - gamma1 and gamma2
### 3 Conditions: [.4, .3]; [.8, .6]; [1.6, 1.2]
# 
# THE FOLLOWING IS A DEMONSTRATION OF HOW YOU WOULD USE A FOR LOOP HERE
# YOU WOULD NEST EVERYTHING WITHIN THE FOR LOOP
# gammas.A <- c(.4, .3)
# gammas.B <- c(.8, .6)
# gammas.C <- c(1.6, 1.2)
# 
# list.of.gammas <- list(gammas.A, gammas.B, gammas.C)
# 
# for (g in 1:3) {
#   whatever.gamma <- list.of.gammas[[g]]
#   gamma1 <- whatever.gamma[1]
#   gamma.2 <- whatever.gamma[2]
# }

#step 1 - generate background variables
N <- 1000 #not going to change when we're just looking at histograms
x1 <- rnorm(N)
x2 <- rbinom(N,1,.5)

b1 <- .1
b2 <- .2
b3 <- .9

equal1 <- -1.8
equal2 <- -0.6
equal3 <- 0.6
equal4 <- 1.8

mild1 <- -1
mild2 <- -0.2
mild3 <- 1
mild4 <- 2.5

severe1 <- 1
severe2 <- 2
severe3 <- 2.5
severe4 <- 3


#step 2 - generate eta
eta <- b1*x1 + b2*x2 + b3*rnorm(N)

#step 3 - generate ystar

gamma1 <- .8
gamma2 <- .6

ystar1 <- gamma1*eta + gamma2*rnorm(N, 0, sd(eta))
# ystar2 <- gamma1*eta + gamma2*rnorm(N, 0, sd(eta))
# ystar3 <- gamma1*eta + gamma2*rnorm(N, 0, sd(eta))
# ystar4 <- gamma1*eta + gamma2*rnorm(N, 0, sd(eta))
# ystar5 <- gamma1*eta + gamma2*rnorm(N, 0, sd(eta))
# ystar6 <- gamma1*eta + gamma2*rnorm(N, 0, sd(eta))
# ystar7 <- gamma1*eta + gamma2*rnorm(N, 0, sd(eta))
# ystar8 <- gamma1*eta + gamma2*rnorm(N, 0, sd(eta))
# ystar9 <- gamma1*eta + gamma2*rnorm(N, 0, sd(eta))
# ystar10 <- gamma1*eta + gamma2*rnorm(N, 0, sd(eta))


#generate y1...y10
#y1- equally spaced
y1<-rep(NA, N)

for (a in 1:N) {
  if (ystar1[a] <= equal1) {
    y1[a] = 1
  }
  else if (ystar1[a] <= equal2) {
    y1[a] = 2
  }
  else if (ystar1[a] <= equal3) {
    y1[a] = 3;
  }
  else if (ystar1[a] <= equal4) {
    y1[a] = 4
  }
  else {
    y1[a] = 5
  }
}
hist(y1)

```

Now, as a demonstration, let's make another histogram

```{r newhistogram}
#This is for demonstration purposes only
y1.weird <- 6 - y1
y1.weirder <- y1 + rnorm(N, 0, 1)

hist(y1.weird)
hist(y1.weirder)

```