---
title: "Mplus Data"
author: "Cassandra Hung"
date: "2024-04-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. G1, B1, N1
```{r, warning = FALSE, message = FALSE}
# 

final_data <- list()

# setwd("C:/Dropbox (Wake Forest University)/collab_2023/Cassi/non-normal/data")
setwd("/Users/cassandrahung/Documents/GitHub/non-normal/data")

library(MplusAutomation)
library(tidyverse)

#path <- "G1_B1_N1/rep1_g1_b1_n1_item1.out"
# output <- readModels("G1_B1_N1/rep1_g1_b1_n1_item1.out")
# output_data <- as.data.frame(output$parameters)
# 
# data <- output_data |>
#   filter((unstandardized.paramHeader == "New.Additional.Parameters") | (unstandardized.paramHeader == "Y1.ON")) |>
#   mutate(condition = str_extract(path, ".+(?=/)"), rep = str_extract(path, "rep\\d+"), item = str_extract(path, "item\\d+"))
  
library(data.table) 
library(rlist)
#
#vector to store/iterate through reps
reps <- 1:500
#vector to store/iterate through items
item <- 1:10

data_list <- list()


for (i in 1:length(reps)) {
  for(j in 1:length(item)) {
  path <- paste0("G1_B1_N1/rep", i, "_g1_b1_n1_item", j, ".out")
  output <- readModels(path)$parameters$unstandardized
  
  output_data <- as.data.frame(output)
    
  y <- paste0("Y", j, ".ON")
    
  data <- output_data |>
  filter((paramHeader == "New.Additional.Parameters")| (paramHeader == y)) |>
    mutate(condition = str_extract(path, ".+(?=/)"), rep = str_extract(path, "(?<=rep)\\d+"), item = str_extract(path, "(?<=item)\\d+"))
    
  #add data frame to list
  data_list <- list.append(data_list, as.data.frame(data))
  }
}

##rbind data_list
final_data[[1]] <- rbindlist(data_list)



# data <- output$parameters
# data <- as.data.frame(data)
```

2. G1, B1, N2
```{r}
#vector to store/iterate through reps
reps <- 1:500
#vector to store/iterate through items
item <- 1:10

data_list <- list()

setwd("/Users/cassandrahung/Documents/GitHub/non-normal/data")


for (i in 1:length(reps)) {
  for(j in 1:length(item)) {
  path <- paste0("G1_B1_N2/rep", i, "_g1_b1_n2_item", j, ".out")
  output <- readModels(path)$parameters$unstandardized
  
  output_data <- as.data.frame(output)
    
  y <- paste0("Y", j, ".ON")
    
  data <- output_data |>
  filter((paramHeader == "New.Additional.Parameters")| (paramHeader == y)) |>
    mutate(condition = str_extract(path, ".+(?=/)"), rep = str_extract(path, "(?<=rep)\\d+"), item = str_extract(path, "(?<=item)\\d+"))
    
  #add data frame to list
  data_list <- list.append(data_list, as.data.frame(data))
  }
}

##rbind data_list
final_data[[2]] <- rbindlist(data_list)
```

3. G1, B1, N3
```{r}

#vector to store/iterate through reps
reps <- 1:500
#vector to store/iterate through items
item <- 1:10

data_list <- list()

setwd("/Users/cassandrahung/Documents/GitHub/non-normal/data")

for (i in 1:length(reps)) {
  for(j in 1:length(item)) {
  path <- paste0("G1_B1_N3/rep", i, "_g1_b1_n3_item", j, ".out")
  output <- readModels(path)$parameters$unstandardized
  
  output_data <- as.data.frame(output)
    
  y <- paste0("Y", j, ".ON")
    
  data <- output_data |>
  filter((paramHeader == "New.Additional.Parameters")| (paramHeader == y)) |>
    mutate(condition = str_extract(path, ".+(?=/)"), rep = str_extract(path, "(?<=rep)\\d+"), item = str_extract(path, "(?<=item)\\d+"))
    
  #add data frame to list
  data_list <- list.append(data_list, as.data.frame(data))
  }
}

##rbind data_list
final_data[[3]] <- rbindlist(data_list)
```


4. G1, B2, N1
```{r}

#vector to store/iterate through reps
reps <- 1:500
#vector to store/iterate through items
item <- 1:10

data_list <- list()

setwd("/Users/cassandrahung/Documents/GitHub/non-normal/data")

for (i in 1:length(reps)) {
  for(j in 1:length(item)) {
  path <- paste0("G1_B2_N1/rep", i, "_g1_b2_n1_item", j, ".out")
  output <- readModels(path)$parameters$unstandardized
  
  output_data <- as.data.frame(output)
    
  y <- paste0("Y", j, ".ON")
    
  data <- output_data |>
  filter((paramHeader == "New.Additional.Parameters")| (paramHeader == y)) |>
    mutate(condition = str_extract(path, ".+(?=/)"), rep = str_extract(path, "(?<=rep)\\d+"), item = str_extract(path, "(?<=item)\\d+"))
    
  #add data frame to list
  data_list <- list.append(data_list, as.data.frame(data))
  }
}

##rbind data_list
final_data[[4]] <- rbindlist(data_list)
```


5. G1, B2, N2
```{r}

#vector to store/iterate through reps
reps <- 1:500
#vector to store/iterate through items
item <- 1:10

data_list <- list()

setwd("/Users/cassandrahung/Documents/GitHub/non-normal/data")

for (i in 1:length(reps)) {
  for(j in 1:length(item)) {
  path <- paste0("G1_B2_N2/rep", i, "_g1_b2_n2_item", j, ".out")
  output <- readModels(path)$parameters$unstandardized
  
  output_data <- as.data.frame(output)
    
  y <- paste0("Y", j, ".ON")
    
  data <- output_data |>
  filter((paramHeader == "New.Additional.Parameters")| (paramHeader == y)) |>
    mutate(condition = str_extract(path, ".+(?=/)"), rep = str_extract(path, "(?<=rep)\\d+"), item = str_extract(path, "(?<=item)\\d+"))
    
  #add data frame to list
  data_list <- list.append(data_list, as.data.frame(data))
  }
}

##rbind data_list
final_data[[5]] <- rbindlist(data_list)
```


6. G1, B2, N3
```{r}

#vector to store/iterate through reps
reps <- 1:500
#vector to store/iterate through items
item <- 1:10

data_list <- list()

setwd("/Users/cassandrahung/Documents/GitHub/non-normal/data")

for (i in 1:length(reps)) {
  for(j in 1:length(item)) {
  path <- paste0("G1_B2_N3/rep", i, "_g1_b2_n3_item", j, ".out")
  output <- readModels(path)$parameters$unstandardized
  
  output_data <- as.data.frame(output)
    
  y <- paste0("Y", j, ".ON")
    
  data <- output_data |>
  filter((paramHeader == "New.Additional.Parameters")| (paramHeader == y)) |>
    mutate(condition = str_extract(path, ".+(?=/)"), rep = str_extract(path, "(?<=rep)\\d+"), item = str_extract(path, "(?<=item)\\d+"))
    
  #add data frame to list
  data_list <- list.append(data_list, as.data.frame(data))
  }
}

##rbind data_list
final_data[[6]] <- rbindlist(data_list)
```

7. G2, B1, N1
```{r}

#vector to store/iterate through reps
reps <- 1:500
#vector to store/iterate through items
item <- 1:10

data_list <- list()

setwd("/Users/cassandrahung/Documents/GitHub/non-normal/data")

for (i in 1:length(reps)) {
  for(j in 1:length(item)) {
  path <- paste0("G2_B1_N1/rep", i, "_g2_b1_n1_item", j, ".out")
  output <- readModels(path)$parameters$unstandardized
  
  output_data <- as.data.frame(output)
    
  y <- paste0("Y", j, ".ON")
    
  data <- output_data |>
  filter((paramHeader == "New.Additional.Parameters")| (paramHeader == y)) |>
    mutate(condition = str_extract(path, ".+(?=/)"), rep = str_extract(path, "(?<=rep)\\d+"), item = str_extract(path, "(?<=item)\\d+"))
    
  #add data frame to list
  data_list <- list.append(data_list, as.data.frame(data))
  }
}

##rbind data_list
final_data[[7]] <- rbindlist(data_list)
```

8. G2, B1, N2
```{r}

#vector to store/iterate through reps
reps <- 1:500
#vector to store/iterate through items
item <- 1:10

data_list <- list()

setwd("/Users/cassandrahung/Documents/GitHub/non-normal/data")

for (i in 1:length(reps)) {
  for(j in 1:length(item)) {
  path <- paste0("G2_B1_N2/rep", i, "_g2_b1_n2_item", j, ".out")
  output <- readModels(path)$parameters$unstandardized
  
  output_data <- as.data.frame(output)
    
  y <- paste0("Y", j, ".ON")
    
  data <- output_data |>
  filter((paramHeader == "New.Additional.Parameters")| (paramHeader == y)) |>
    mutate(condition = str_extract(path, ".+(?=/)"), rep = str_extract(path, "(?<=rep)\\d+"), item = str_extract(path, "(?<=item)\\d+"))
    
  #add data frame to list
  data_list <- list.append(data_list, as.data.frame(data))
  }
}

##rbind data_list
final_data[[8]] <- rbindlist(data_list)
```

9. G2, B1, N3
```{r}

#vector to store/iterate through reps
reps <- 1:500
#vector to store/iterate through items
item <- 1:10

data_list <- list()

setwd("/Users/cassandrahung/Documents/GitHub/non-normal/data")

for (i in 1:length(reps)) {
  for(j in 1:length(item)) {
  path <- paste0("G2_B1_N3/rep", i, "_g2_b1_n3_item", j, ".out")
  output <- readModels(path)$parameters$unstandardized
  
  output_data <- as.data.frame(output)
    
  y <- paste0("Y", j, ".ON")
    
  data <- output_data |>
  filter((paramHeader == "New.Additional.Parameters")| (paramHeader == y)) |>
    mutate(condition = str_extract(path, ".+(?=/)"), rep = str_extract(path, "(?<=rep)\\d+"), item = str_extract(path, "(?<=item)\\d+"))
    
  #add data frame to list
  data_list <- list.append(data_list, as.data.frame(data))
  }
}

##rbind data_list
final_data[[9]] <- rbindlist(data_list)
```


10. G2, B2, N1
```{r}

#vector to store/iterate through reps
reps <- 1:500
#vector to store/iterate through items
item <- 1:10

data_list <- list()

setwd("/Users/cassandrahung/Documents/GitHub/non-normal/data")

for (i in 1:length(reps)) {
  for(j in 1:length(item)) {
  path <- paste0("G2_B2_N1/rep", i, "_g2_b2_n1_item", j, ".out")
  output <- readModels(path)$parameters$unstandardized
  
  output_data <- as.data.frame(output)
    
  y <- paste0("Y", j, ".ON")
    
  data <- output_data |>
  filter((paramHeader == "New.Additional.Parameters")| (paramHeader == y)) |>
    mutate(condition = str_extract(path, ".+(?=/)"), rep = str_extract(path, "(?<=rep)\\d+"), item = str_extract(path, "(?<=item)\\d+"))
    
  #add data frame to list
  data_list <- list.append(data_list, as.data.frame(data))
  }
}

##rbind data_list
final_data[[10]] <- rbindlist(data_list)
```

11. G2, B2, N2
```{r}

#vector to store/iterate through reps
reps <- 1:500
#vector to store/iterate through items
item <- 1:10

data_list <- list()

setwd("/Users/cassandrahung/Documents/GitHub/non-normal/data")

for (i in 1:length(reps)) {
  for(j in 1:length(item)) {
  path <- paste0("G2_B2_N2/rep", i, "_g2_b2_n2_item", j, ".out")
  output <- readModels(path)$parameters$unstandardized
  
  output_data <- as.data.frame(output)
    
  y <- paste0("Y", j, ".ON")
    
  data <- output_data |>
  filter((paramHeader == "New.Additional.Parameters")| (paramHeader == y)) |>
    mutate(condition = str_extract(path, ".+(?=/)"), rep = str_extract(path, "(?<=rep)\\d+"), item = str_extract(path, "(?<=item)\\d+"))
    
  #add data frame to list
  data_list <- list.append(data_list, as.data.frame(data))
  }
}

##rbind data_list
final_data[[11]] <- rbindlist(data_list)
```

12. G2, B2, N3
```{r}

#vector to store/iterate through reps
reps <- 1:500
#vector to store/iterate through items
item <- 1:10

data_list <- list()

setwd("/Users/cassandrahung/Documents/GitHub/non-normal/data")

for (i in 1:length(reps)) {
  for(j in 1:length(item)) {
  path <- paste0("G2_B2_N3/rep", i, "_g2_b2_n3_item", j, ".out")
  output <- readModels(path)$parameters$unstandardized
  
  output_data <- as.data.frame(output)
    
  y <- paste0("Y", j, ".ON")
    
  data <- output_data |>
  filter((paramHeader == "New.Additional.Parameters")| (paramHeader == y)) |>
    mutate(condition = str_extract(path, ".+(?=/)"), rep = str_extract(path, "(?<=rep)\\d+"), item = str_extract(path, "(?<=item)\\d+"))
    
  #add data frame to list
  data_list <- list.append(data_list, as.data.frame(data))
  }
}

##rbind data_list
final_data[[12]] <- rbindlist(data_list)
```

13. G3, B1, N1
```{r}

#vector to store/iterate through reps
reps <- 1:500
#vector to store/iterate through items
item <- 1:10

data_list <- list()

setwd("/Users/cassandrahung/Documents/GitHub/non-normal/data")

for (i in 1:length(reps)) {
  for(j in 1:length(item)) {
  path <- paste0("G3_B1_N1/rep", i, "_g3_b1_n1_item", j, ".out")
  output <- readModels(path)$parameters$unstandardized
  
  output_data <- as.data.frame(output)
    
  y <- paste0("Y", j, ".ON")
    
  data <- output_data |>
  filter((paramHeader == "New.Additional.Parameters")| (paramHeader == y)) |>
    mutate(condition = str_extract(path, ".+(?=/)"), rep = str_extract(path, "(?<=rep)\\d+"), item = str_extract(path, "(?<=item)\\d+"))
    
  #add data frame to list
  data_list <- list.append(data_list, as.data.frame(data))
  }
}

##rbind data_list
final_data[[13]] <- rbindlist(data_list)
```

14. G3, B1, N2
```{r}

#vector to store/iterate through reps
reps <- 1:500
#vector to store/iterate through items
item <- 1:10

data_list <- list()

setwd("/Users/cassandrahung/Documents/GitHub/non-normal/data")

for (i in 1:length(reps)) {
  for(j in 1:length(item)) {
  path <- paste0("G3_B1_N2/rep", i, "_g3_b1_n2_item", j, ".out")
  output <- readModels(path)$parameters$unstandardized
  
  output_data <- as.data.frame(output)
    
  y <- paste0("Y", j, ".ON")
    
  data <- output_data |>
  filter((paramHeader == "New.Additional.Parameters")| (paramHeader == y)) |>
    mutate(condition = str_extract(path, ".+(?=/)"), rep = str_extract(path, "(?<=rep)\\d+"), item = str_extract(path, "(?<=item)\\d+"))
    
  #add data frame to list
  data_list <- list.append(data_list, as.data.frame(data))
  }
}

##rbind data_list
final_data[[14]] <- rbindlist(data_list)
```

15. G3, B1, N3
```{r}

#vector to store/iterate through reps
reps <- 1:500
#vector to store/iterate through items
item <- 1:10

data_list <- list()

setwd("/Users/cassandrahung/Documents/GitHub/non-normal/data")

for (i in 1:length(reps)) {
  for(j in 1:length(item)) {
  path <- paste0("G3_B1_N3/rep", i, "_g3_b1_n3_item", j, ".out")
  output <- readModels(path)$parameters$unstandardized
  
  output_data <- as.data.frame(output)
    
  y <- paste0("Y", j, ".ON")
    
  data <- output_data |>
  filter((paramHeader == "New.Additional.Parameters")| (paramHeader == y)) |>
    mutate(condition = str_extract(path, ".+(?=/)"), rep = str_extract(path, "(?<=rep)\\d+"), item = str_extract(path, "(?<=item)\\d+"))
    
  #add data frame to list
  data_list <- list.append(data_list, as.data.frame(data))
  }
}

##rbind data_list
final_data[[15]] <- rbindlist(data_list)
```

16. G3, B2, N1
```{r}

#vector to store/iterate through reps
reps <- 1:500
#vector to store/iterate through items
item <- 1:10

data_list <- list()

setwd("/Users/cassandrahung/Documents/GitHub/non-normal/data")

for (i in 1:length(reps)) {
  for(j in 1:length(item)) {
  path <- paste0("G3_B2_N1/rep", i, "_g3_b2_n1_item", j, ".out")
  output <- readModels(path)$parameters$unstandardized
  
  output_data <- as.data.frame(output)
    
  y <- paste0("Y", j, ".ON")
    
  data <- output_data |>
  filter((paramHeader == "New.Additional.Parameters")| (paramHeader == y)) |>
    mutate(condition = str_extract(path, ".+(?=/)"), rep = str_extract(path, "(?<=rep)\\d+"), item = str_extract(path, "(?<=item)\\d+"))
    
  #add data frame to list
  data_list <- list.append(data_list, as.data.frame(data))
  }
}

##rbind data_list
final_data[[16]] <- rbindlist(data_list)
```

17. G3, B2, N2
```{r}

#vector to store/iterate through reps
reps <- 1:500
#vector to store/iterate through items
item <- 1:10

data_list <- list()

setwd("/Users/cassandrahung/Documents/GitHub/non-normal/data")

for (i in 1:length(reps)) {
  for(j in 1:length(item)) {
  path <- paste0("G3_B2_N2/rep", i, "_g3_b2_n2_item", j, ".out")
  output <- readModels(path)$parameters$unstandardized
  
  output_data <- as.data.frame(output)
    
  y <- paste0("Y", j, ".ON")
    
  data <- output_data |>
  filter((paramHeader == "New.Additional.Parameters")| (paramHeader == y)) |>
    mutate(condition = str_extract(path, ".+(?=/)"), rep = str_extract(path, "(?<=rep)\\d+"), item = str_extract(path, "(?<=item)\\d+"))
    
  #add data frame to list
  data_list <- list.append(data_list, as.data.frame(data))
  }
}

##rbind data_list
final_data[[17]] <- rbindlist(data_list)
```

18. G3, B2, N3
```{r}

#vector to store/iterate through reps
reps <- 1:500
#vector to store/iterate through items
item <- 1:10

data_list <- list()

setwd("/Users/cassandrahung/Documents/GitHub/non-normal/data")

for (i in 1:length(reps)) {
  for(j in 1:length(item)) {
  path <- paste0("G3_B2_N3/rep", i, "_g3_b2_n3_item", j, ".out")
  output <- readModels(path)$parameters$unstandardized
  
  output_data <- as.data.frame(output)
    
  y <- paste0("Y", j, ".ON")
    
  data <- output_data |>
  filter((paramHeader == "New.Additional.Parameters")| (paramHeader == y)) |>
    mutate(condition = str_extract(path, ".+(?=/)"), rep = str_extract(path, "(?<=rep)\\d+"), item = str_extract(path, "(?<=item)\\d+"))
    
  #add data frame to list
  data_list <- list.append(data_list, as.data.frame(data))
  }
}

##rbind data_list
final_data[[18]] <- rbindlist(data_list)

final_dataframe <- rbindlist(final_data)
```

```{r}
setwd("/Users/cassandrahung/Documents/GitHub/non-normal/data")
write.csv(final_dataframe, file="data.csv")
```
```{r}
# Tabulating data

# y1, y2, y9, y10 = mild
# y3, y4, y5 = equal
# y6, y7, y8 = severe

library(tidyverse)

# test <- final_data[[1]] |>
#   filter((item == 6 | item == 7 | item == 8) & str_detect(param, "X2")) |>
#   summarize(mean_x2 = mean(pval))
# 
# g1b1n1_mild <- final_data[[1]] |>
#   mutate(skew = "mild") |>
#   filter((item == 1 | item == 2 | item == 9 | item == 10) & !str_detect(param, "_0")) |>
#   mutate(param1 = case_when(
#     param == "X1" ~ "X1",
#     param == "X2" ~ "X2",
#     str_detect(param, "_1") ~ "L_1",
#     str_detect(param, "_2") ~ "L_2"
#   )) |>
#   group_by(param1, condition, skew) |>
#   summarize(mean_param = mean(est), mean_pval = mean(pval))
# 
# g1b1n1_equal <- final_data[[1]] |>
#   filter((item == 3 | item == 4 | item == 5) & !str_detect(param, "_0")) |>
#   mutate(param1 = case_when(
#     param == "X1" ~ "X1",
#     param == "X2" ~ "X2",
#     str_detect(param, "_1") ~ "L_1",
#     str_detect(param, "_2") ~ "L_2"
#   )) |>
#   group_by(param1, condition) |>
#   summarize(mean = mean(est), mean_pval = mean(pval))
# 
# g1b1n1_severe <- final_data[[1]] |>
#   filter((item == 6 | item == 7 | item == 8) & !str_detect(param, "_0")) |>
#   mutate(param1 = case_when(
#     param == "X1" ~ "X1",
#     param == "X2" ~ "X2",
#     str_detect(param, "_1") ~ "L_1",
#     str_detect(param, "_2") ~ "L_2"
#   )) |>
#   group_by(param1, condition) |>
#   summarize(mean = mean(est), mean_pval = mean(pval))



summarized_data <- list()

for(i in 1:length(final_data)) {
  
  # Mean estimates and p-values for mild skew
  mild <- final_data[[i]] |>
  mutate(skew = "mild") |>
  filter((item == 1 | item == 2 | item == 9 | item == 10) & !str_detect(param, "_0")) |>
  mutate(param1 = case_when(
    param == "X1" ~ "X1",
    param == "X2" ~ "X2",
    str_detect(param, "_1") ~ "L_1",
    str_detect(param, "_2") ~ "L_2"
  )) |>
  group_by(param1, condition, skew) |>
  summarize(mean_param = mean(est), type1_error_rate = mean(pval < 0.05))
  
  summarized_data <- list.append(summarized_data, mild)

   # Mean estimates and p-values for equally distributed
  equal <- final_data[[i]] |>
    mutate(skew = "equal") |>
    filter((item == 3 | item == 4 | item == 5) & !str_detect(param, "_0")) |>
    mutate(param1 = case_when(
      param == "X1" ~ "X1",
      param == "X2" ~ "X2",
      str_detect(param, "_1") ~ "L_1",
      str_detect(param, "_2") ~ "L_2"
    )) |>
    group_by(param1, condition, skew) |>
    summarize(mean = mean(est), type1_error_rate = mean(pval < 0.05))
  
  summarized_data <- list.append(summarized_data, equal)

  # Mean estimates and p-values for severe skew
  severe <- final_data[[i]] |>
    mutate(skew = "severe") |>
    filter((item == 6 | item == 7 | item == 8) & !str_detect(param, "_0")) |>
    mutate(param1 = case_when(
      param == "X1" ~ "X1",
      param == "X2" ~ "X2",
      str_detect(param, "_1") ~ "L_1",
      str_detect(param, "_2") ~ "L_2"
    )) |>
    group_by(param1, condition, skew) |>
    summarize(mean = mean(est), type1_error_rate = mean(pval < 0.05))
  
  summarized_data <- list.append(summarized_data, severe)
  
}

tabulated_data <- rbindlist(summarized_data)

setwd("/Users/cassandrahung/Documents/GitHub/non-normal/data")
write.csv(tabulated_data, file="tabulated_data(with error rates).csv")
  
```

